### ISSUE TITLE
Ambiguity in named entity category is incorrectly resolved for the names that are both territories and organizations

### ISSUE THREAD

**Issue by KOLANICH** [natasha/natasha#95]
I.e. `Украина` in the example is sometimes used as a territory (`на Украине`, though de-facto in this context this means Ukraine as an org, but syntaxicaly it is used as a territory), and sometimes as a name of an org (`Украина не должна`, `против Украины`). Feel like the lib should distinguish this 2 cases. Since the disctinctions is fuzzy, it should be a probability distribution rather than just a label.

**Comment by kuk** [comment]
The problem was addressed if FactRuEval, they use LOCORG label in addition to LOC and ORG. In practice it results in number of problems, see https://github.com/dialogue-evaluation/factRuEval-2016/issues/12 for example, it becomes harder to annotate training dataset. So we just treat all LOCORG entities as LOC.
